-- ==============================================================================
-- PROJET HELLMETZ : Script de création de la base de données
-- Cible : PostgreSQL (>= 12)
-- Description : Modèle de données complet avec enrichissements métier (RH, Logistique, Com)
-- ==============================================================================

-- 1. Nettoyage et préparation du schéma (rejouable à l'infini)
DROP SCHEMA IF EXISTS hellmetz CASCADE;
CREATE SCHEMA hellmetz;
SET search_path TO hellmetz;

-- ==============================================================================
-- 2. CRÉATION DES TABLES RÉFÉRENTIELLES (Sans clés étrangères)
-- ==============================================================================

CREATE TABLE affectation (
  id_affectation bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statut varchar(120) NOT NULL DEFAULT 'En attente'
);

CREATE TABLE categorie_article (
  id_categorie_article bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120) NOT NULL,
  description text
);

CREATE TABLE categorie_materiel (
  id_categorie_materiel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120) NOT NULL,
  description text
);

CREATE TABLE role (
  id_role bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_role varchar(50) NOT NULL UNIQUE,
  libelle varchar(120) NOT NULL
);

CREATE TABLE permission (
  id_permission bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_permission varchar(50) NOT NULL UNIQUE,
  libelle varchar(120) NOT NULL,
  description text
);

CREATE TABLE style (
  id_style bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120) NOT NULL,
  description text
);

CREATE TABLE type_stand (
  id_type_stand bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120) NOT NULL,
  description text
);

CREATE TABLE scene (
  id_scene bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_scene varchar(255) NOT NULL,
  description text,
  capacite integer CHECK (capacite > 0),
  actif boolean DEFAULT true,
  -- Enrichissements Logistique :
  type_scene varchar(50), 
  superficie_m2 integer,
  url_plan_technique varchar(255)
);

CREATE TABLE client (
  id_client bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(120) NOT NULL,
  prenom varchar(120) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  telephone varchar(30),
  actif boolean DEFAULT true,
  date_creation timestamp DEFAULT CURRENT_TIMESTAMP,
  -- Enrichissements Marketing :
  date_naissance date,
  accepte_newsletter boolean DEFAULT false
);

CREATE TABLE edition_festival (
  id_edition bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annee integer NOT NULL CHECK (annee > 2000),
  nom_edition varchar(255) NOT NULL,
  date_debut timestamp NOT NULL,
  date_fin timestamp NOT NULL,
  lattitude numeric(9,6),
  longitude numeric(9,6),
  lieu varchar(120) NOT NULL,
  -- Enrichissements Direction :
  theme varchar(255),
  url_affiche_officielle varchar(255),
  budget_previsionnel numeric(12,2),
  jauge_maximale integer
);

-- ==============================================================================
-- 3. CRÉATION DES TABLES AVEC DÉPENDANCES (Niveau 1)
-- ==============================================================================

CREATE TABLE utilisateur (
  id_utilisateur bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  identifiant varchar(100) NOT NULL UNIQUE,
  mot_de_passe varchar(255) NOT NULL,
  nom varchar(120) NOT NULL,
  prenom varchar(120) NOT NULL,
  actif boolean DEFAULT true,
  date_creation timestamp DEFAULT CURRENT_TIMESTAMP,
  derniere_connexion timestamp
);

CREATE TABLE benevole (
  id_benevole bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(120) NOT NULL,
  prenom varchar(120) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  telephone varchar(30),
  actif boolean DEFAULT true,
  id_affectation bigint REFERENCES affectation (id_affectation) ON DELETE SET NULL,
  -- Enrichissements Ressources Humaines (RH) :
  taille_tshirt varchar(10), 
  date_naissance date, 
  restrictions_alimentaires text, 
  contact_urgence_nom varchar(120),
  contact_urgence_telephone varchar(30),
  permis_conduire boolean DEFAULT false
);

CREATE TABLE poste (
  id_poste bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120) NOT NULL,
  description text,
  id_affectation bigint REFERENCES affectation (id_affectation) ON DELETE CASCADE
);

CREATE TABLE artiste (
  id_artiste bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar(120),
  prenom varchar(120),
  nom_scene varchar(120) NOT NULL,
  biographie text,
  url_photo varchar(255),
  id_style bigint REFERENCES style (id_style) ON DELETE SET NULL,
  -- Enrichissements Programmation :
  nationalite varchar(100),
  cachet numeric(10,2), 
  url_facebook varchar(255),
  url_instagram varchar(255),
  url_spotify varchar(255),
  exigences_catering text
);

CREATE TABLE article (
  id_article bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre varchar(255) NOT NULL,
  description text,
  actif boolean DEFAULT true,
  prix_ht numeric(10,2) NOT NULL CHECK (prix_ht >= 0),
  taux_tva numeric(10,2) NOT NULL CHECK (taux_tva >= 0),
  image varchar(255),
  date_creation timestamp DEFAULT CURRENT_TIMESTAMP,
  poids_grammes integer CHECK (poids_grammes >= 0),
  -- Enrichissements Billetterie & Merch :
  code_barre varchar(50), 
  est_dematerialise boolean DEFAULT false, 
  stock_illimite boolean DEFAULT false
);

CREATE TABLE materiel (
  id_materiel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference varchar(255) NOT NULL,
  marque varchar(255),
  modele varchar(255),
  description text,
  etat varchar(120) DEFAULT 'Neuf',
  actif boolean DEFAULT true,
  id_categorie_materiel bigint REFERENCES categorie_materiel (id_categorie_materiel) ON DELETE SET NULL,
  -- Enrichissements Technique :
  numero_serie varchar(255), 
  date_achat date,
  prix_achat numeric(10,2),
  valeur_assurance numeric(10,2)
);

CREATE TABLE stand (
  id_stand bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_stand varchar(120) NOT NULL,
  description text,
  lattitude numeric(9,6),
  longitude numeric(9,6),
  emplacement varchar(120),
  actif boolean DEFAULT true,
  id_type_stand bigint REFERENCES type_stand (id_type_stand) ON DELETE SET NULL,
  -- Enrichissements Logistique :
  besoin_electrique_kw numeric(5,2), 
  point_eau_necessaire boolean DEFAULT false, 
  fournisseur_externe boolean DEFAULT false
);

-- ==============================================================================
-- 4. CRÉATION DES TABLES D'ACTIVITÉ (Concerts, Stocks, Ventes)
-- ==============================================================================

CREATE TABLE concert (
  id_concert bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_heure_debut timestamp NOT NULL,
  date_heure_fin timestamp NOT NULL,
  statut varchar(120) DEFAULT 'Programmé',
  id_scene bigint REFERENCES scene (id_scene) ON DELETE SET NULL,
  id_edition bigint REFERENCES edition_festival (id_edition) ON DELETE CASCADE,
  -- Enrichissements Régie :
  heure_balance_debut timestamp, 
  heure_balance_fin timestamp,
  decibels_max integer DEFAULT 102
);

CREATE TABLE groupe (
  id_groupe bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom_groupe varchar(255) NOT NULL,
  description text,
  actif boolean DEFAULT true,
  id_concert bigint REFERENCES concert (id_concert) ON DELETE SET NULL,
  -- Enrichissements Communication & Technique :
  annee_creation integer CHECK (annee_creation > 1900),
  ville_origine varchar(120),
  pays_origine varchar(120) DEFAULT 'France',
  url_logo varchar(255),
  site_web varchar(255),
  url_facebook varchar(255),
  url_instagram varchar(255),
  url_youtube varchar(255),
  url_spotify varchar(255),
  email_contact varchar(255),
  telephone_contact varchar(30),
  url_fiche_technique varchar(255) 
);

CREATE TABLE point_stock (
  id_point_stock bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_point_stock varchar(120) NOT NULL,
  libelle varchar(120) NOT NULL,
  description text,
  id_stand bigint REFERENCES stand (id_stand) ON DELETE CASCADE
);

CREATE TABLE stock (
  id_stock bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantite_disponible integer NOT NULL DEFAULT 0 CHECK (quantite_disponible >= 0),
  quantite_reservee integer NOT NULL DEFAULT 0 CHECK (quantite_reservee >= 0),
  seuil_alerte integer DEFAULT 0 CHECK (seuil_alerte >= 0),
  date_maj timestamp DEFAULT CURRENT_TIMESTAMP,
  id_article bigint REFERENCES article (id_article) ON DELETE CASCADE,
  id_point_stock bigint REFERENCES point_stock (id_point_stock) ON DELETE CASCADE
);

CREATE TABLE mouvement_stock (
  id_mouvement_stock bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_mouvement varchar(120) NOT NULL,
  quantite integer NOT NULL,
  date_mouvement timestamp DEFAULT CURRENT_TIMESTAMP,
  commentaire text,
  id_stock bigint REFERENCES stock (id_stock) ON DELETE CASCADE
);

CREATE TABLE emprunt_materiel (
  id_emprunt bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_sortie timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_retour_prevue timestamp NOT NULL,
  date_retour_reelle timestamp,
  quantite integer NOT NULL CHECK (quantite > 0),
  statut varchar(120) DEFAULT 'En cours',
  commentaire text,
  id_concert bigint REFERENCES concert (id_concert) ON DELETE CASCADE,
  id_materiel bigint REFERENCES materiel (id_materiel) ON DELETE CASCADE
);

CREATE TABLE plage_horaire (
  id_creneau bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_heure_debut timestamp NOT NULL,
  date_heure_fin timestamp NOT NULL,
  type_creneau varchar(120),
  id_affectation bigint REFERENCES affectation (id_affectation) ON DELETE SET NULL,
  id_edition bigint REFERENCES edition_festival (id_edition) ON DELETE CASCADE
);

-- ==============================================================================
-- 5. GESTION COMMERCIALE (Commandes, Paiements, Livraisons)
-- ==============================================================================

CREATE TABLE paiement (
  id_paiement bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_paiement timestamp DEFAULT CURRENT_TIMESTAMP,
  mode_paiement varchar(120) NOT NULL,
  statut_paiement varchar(120) DEFAULT 'En attente',
  montant numeric(10,2) NOT NULL CHECK (montant >= 0),
  reference_transaction varchar(255)
);

CREATE TABLE livraison (
  id_livraison bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_prevue timestamp,
  date_expedition timestamp,
  date_livraison timestamp,
  statut_livraison varchar(120) DEFAULT 'Préparation',
  transporteur varchar(255),
  numero_suivi varchar(255)
);

CREATE TABLE commande (
  id_commande bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_commande timestamp DEFAULT CURRENT_TIMESTAMP,
  statut_commande varchar(120) DEFAULT 'Nouvelle',
  total_ht numeric(10,2) NOT NULL DEFAULT 0 CHECK (total_ht >= 0),
  total_tva numeric(10,2) NOT NULL DEFAULT 0 CHECK (total_tva >= 0),
  total_ttc numeric(10,2) NOT NULL DEFAULT 0 CHECK (total_ttc >= 0),
  id_client bigint REFERENCES client (id_client) ON DELETE CASCADE,
  id_paiement bigint REFERENCES paiement (id_paiement) ON DELETE SET NULL,
  id_livraison bigint REFERENCES livraison (id_livraison) ON DELETE SET NULL
);

CREATE TABLE adresse (
  id_adresse bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle varchar(120),
  nom_destinataire varchar(120) NOT NULL,
  prenom_destinataire varchar(120) NOT NULL,
  ligne1 varchar(255) NOT NULL,
  ligne2 varchar(255),
  code_postal varchar(50) NOT NULL,
  ville varchar(255) NOT NULL,
  pays varchar(255) DEFAULT 'France',
  instruction_livraison varchar(255),
  telephone_destinataire varchar(30),
  id_commande bigint REFERENCES commande (id_commande) ON DELETE CASCADE,
  id_client bigint REFERENCES client (id_client) ON DELETE CASCADE 
);

CREATE TABLE ligne_commande (
  id_ligne_commande bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantite integer NOT NULL CHECK (quantite > 0),
  prix_unitaire_ht numeric(10,2) NOT NULL CHECK (prix_unitaire_ht >= 0),
  total_ligne_ht numeric(10,2) NOT NULL CHECK (total_ligne_ht >= 0),
  id_article bigint REFERENCES article (id_article) ON DELETE RESTRICT,
  id_commande bigint REFERENCES commande (id_commande) ON DELETE CASCADE
);

CREATE TABLE vente_stand (
  id_vente_stand bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_heure_vente timestamp DEFAULT CURRENT_TIMESTAMP,
  mode_paiement varchar(120) NOT NULL,
  statut_vente varchar(120) DEFAULT 'Validée',
  total_ttc numeric(10,2) NOT NULL CHECK (total_ttc >= 0),
  id_stand bigint REFERENCES stand (id_stand) ON DELETE SET NULL
);

CREATE TABLE ligne_vente_stand (
  id_ligne_vente_stand bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantite integer NOT NULL CHECK (quantite > 0),
  prix_unitaire_ht numeric(10,2) NOT NULL CHECK (prix_unitaire_ht >= 0),
  total_ligne_ht numeric(10,2) NOT NULL CHECK (total_ligne_ht >= 0),
  id_vente_stand bigint REFERENCES vente_stand (id_vente_stand) ON DELETE CASCADE,
  id_article bigint REFERENCES article (id_article) ON DELETE RESTRICT
);

-- ==============================================================================
-- 6. TABLES DE LIAISONS (Many-to-Many)
-- ==============================================================================

CREATE TABLE article_categorie_article (
  id_categorie_article bigint REFERENCES categorie_article (id_categorie_article) ON DELETE CASCADE,
  id_article bigint REFERENCES article (id_article) ON DELETE CASCADE,
  PRIMARY KEY (id_categorie_article, id_article)
);

CREATE TABLE role_permission (
  id_permission bigint REFERENCES permission (id_permission) ON DELETE CASCADE,
  id_role bigint REFERENCES role (id_role) ON DELETE CASCADE,
  PRIMARY KEY (id_permission, id_role)
);

CREATE TABLE role_utilisateur (
  id_utilisateur bigint REFERENCES utilisateur (id_utilisateur) ON DELETE CASCADE,
  id_role bigint REFERENCES role (id_role) ON DELETE CASCADE,
  PRIMARY KEY (id_utilisateur, id_role)
);

-- 2. On ajoute la bonne colonne dans la table "artiste"
ALTER TABLE artiste ADD COLUMN id_groupe bigint;

-- 3. On crée la contrainte de clé étrangère
ALTER TABLE artiste 
  ADD CONSTRAINT fk_artiste_groupe 
  FOREIGN KEY (id_groupe) REFERENCES groupe (id_groupe) ON DELETE CASCADE;

-- Fin du script